import { 
    MergeIcon, 
    SplitIcon, 
    CompressIcon, 
    RotateIcon, 
    ImageToPdfIcon, 
    WordToPdfIcon, 
    PageNumberIcon,
    OrganizeIcon,
    PdfToJpgIcon,
    WatermarkIcon,
    PowerpointToPdfIcon,
    ExcelToPdfIcon,
    PdfToWordIcon,
    PdfToPowerpointIcon,
    PdfToExcelIcon,
    CropIcon,
} from './components/icons';
import type { Tool } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDFs into a single document.',
    icon: MergeIcon,
    color: 'text-indigo-500',
    category: 'Organize PDF',
  },
  {
    id: 'split-pdf',
    title: 'Split PDF',
    description: 'Extract pages or save each page as a separate PDF.',
    icon: SplitIcon,
    color: 'text-yellow-500',
    category: 'Organize PDF',
  },
  {
    id: 'organize-pdf',
    title: 'Organize PDF',
    description: 'Reorder, rotate, and delete pages visually.',
    icon: OrganizeIcon,
    color: 'text-cyan-500',
    category: 'Organize PDF',
  },
  {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate one or all pages in your PDF document.',
    icon: RotateIcon,
    color: 'text-blue-500',
    category: 'Edit PDF',
  },
  {
    id: 'add-page-numbers',
    title: 'Add Page Numbers',
    description: 'Insert page numbers into your PDF document easily.',
    icon: PageNumberIcon,
    color: 'text-rose-500',
    category: 'Edit PDF',
  },
  {
    id: 'add-watermark',
    title: 'Add watermark',
    description: 'Stamp an image or text over your PDF in seconds.',
    icon: WatermarkIcon,
    color: 'text-lime-500',
    category: 'Edit PDF',
  },
  {
    id: 'crop-pdf',
    title: 'Crop PDF',
    description: 'Trim the margins of your PDF pages.',
    icon: CropIcon,
    color: 'text-orange-500',
    category: 'Edit PDF',
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    description: 'Convert JPG, PNG, and other images to PDF.',
    icon: ImageToPdfIcon,
    color: 'text-purple-500',
    category: 'Convert PDF',
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Extract all images from a PDF or convert pages to JPG.',
    icon: PdfToJpgIcon,
    color: 'text-fuchsia-500',
    category: 'Convert PDF',
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce the file size of your PDF while maintaining quality.',
    icon: CompressIcon,
    color: 'text-green-500',
    category: 'Optimize PDF',
    disabled: true,
  },
  {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Easily convert your Microsoft Word documents to PDF.',
    icon: WordToPdfIcon,
    color: 'text-sky-500',
    category: 'Convert PDF',
    disabled: true,
  },
  {
    id: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF documents.',
    icon: PowerpointToPdfIcon,
    color: 'text-red-600',
    category: 'Convert PDF',
    disabled: true,
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF documents.',
    icon: ExcelToPdfIcon,
    color: 'text-emerald-600',
    category: 'Convert PDF',
    disabled: true,
  },
  {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert PDFs to editable Word documents.',
    icon: PdfToWordIcon,
    color: 'text-sky-600',
    category: 'Convert PDF',
    disabled: true,
  },
  {
    id: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    description: 'Convert PDFs to editable PowerPoint presentations.',
    icon: PdfToPowerpointIcon,
    color: 'text-red-700',
    category: 'Convert PDF',
    disabled: true,
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Convert PDFs to editable Excel spreadsheets.',
    icon: PdfToExcelIcon,
    color: 'text-emerald-700',
    category: 'Convert PDF',
    disabled: true,
  },
];